### ISSUE TITLE
Broken link in the documentation - Introduction to Extensions

### ISSUE THREAD

**Issue by sgera** [AdobeDocs/project-firefly#113]
### Actual Behaviour
In the documentation (https://www.adobe.io/project-firefly/docs/guides/extensions/), the link for “Creating your First Project Firefly Application”(https://www.adobe.io/project-firefly/docs/first_app.md) is broken. Here's what we get after clicking on that link - 

![image](https://user-images.githubusercontent.com/5928555/127625410-758bcd19-6fce-4b26-b838-3aece925464d.png)

### Expected Behaviour
Probably the correct link is https://www.adobe.io/project-firefly/docs/getting_started/first_app/. 

#### Steps to Reproduce
1. Go to https://www.adobe.io/project-firefly/docs/guides/extensions/
2. Click on “Creating your First Project Firefly Application” link

**Comment by sgera** [comment]
cc: @icaraps @meryllblanchet

**Comment by icaraps** [comment]
@sgera Thanks for reporting the broken link ! The fix is being deployed https://github.com/AdobeDocs/project-firefly/runs/3200199866?check_suite_focus=true.
