### ISSUE TITLE
SFTP from worker

### ISSUE THREAD

**Issue by jstadler1218** [AdobeDocs/project-firefly#119]
Issue in /src/pages/getting_started/index.md

We are looking to integrate SFTP import and export with Adobe Experience Manager as a Cloud Service. We have run into issue where previous Java implementation in on-premise AEM no longer is possible in Cloud Services due to restrictions in network ports to/from AEMaaCS. Our team is now exploring using Adobe IO and project firefly worker to be the SFTP client. Are there any restrictions with connectivity to/from Project Firefly workers?

**Comment by meryllblanchet** [comment]
Hi @jstadler1218 , this is totally possible. You just need to use an npm module such as https://www.npmjs.com/package/ssh2-sftp-client within your Runtime action.

Please note that this kind of practical question will get better visibility and support if you reach out to the team on our [Experience League forum](https://experienceleaguecommunities.adobe.com/t5/project-firefly/ct-p/project-firefly).
