### ISSUE TITLE
Renamed extension point ❯◉ Firefly Experience Cloud Shell

### ISSUE THREAD

**Issue by synox** [AdobeDocs/project-firefly#151]
### Expected Behaviour
Documentation lists extension point `Firefly Experience Cloud Shell`. But only `DX Experience Cloud SPA v1` is selectable. 

Docs https://www.adobe.io/app-builder/docs/getting_started/first_app/#41-developer-is-logged-in-as-enterprise-organization-user  should mention `DX Experience Cloud SPA v1`.

### Actual Behaviour

-

#### Steps to Reproduce
fresh project according to the https://www.adobe.io/app-builder/docs/getting_started/first_app

**Comment by godanny86** [comment]
Plus one to this ^

**Comment by shazron** [comment]
PR https://github.com/AdobeDocs/project-firefly/pull/176
