### ISSUE TITLE
manifest.yml does not exist

### ISSUE THREAD

**Issue by synox** [AdobeDocs/project-firefly#152]
### Expected Behaviour

https://www.adobe.io/app-builder/docs/getting_started/first_app/#62-trying-the-sample-application mentions 

> All actions require Authorization and x-gw-ims-org-id in the headers by default. In your project code, if you navigate to **manifest.yml**, you can see that a require-adobe-auth annotation is set to true for all the sample actions. 

However, I don't have such a file in the newly created project. I see `ext.config.yaml`, is this what you mean? 

### Actual Behaviour

docs do not match project.

**Comment by shazron** [comment]
Fixed
