### ISSUE TITLE
Links need an update

### ISSUE THREAD

**Issue by td-heinm** [AdobeDocs/project-firefly#183]
src: https://github.com/AdobeDocs/project-firefly/blob/main/src/pages/guides/security/understanding_authentication.md
live page: https://developer.adobe.com/app-builder/docs/guides/security/understanding_authentication/

Bad links lead to an **ERROR 404: Page not found**: 
1. for [OAuth 2.0 Authentication and Authorization](https://developer.adobe.com/authentication/auth-methods#!AdobeDocs/adobeio-auth/master/OAuth/OAuth.md)
2.  [This document](https://developer.adobe.com/authentication/auth-methods#!AdobeDocs/adobeio-auth/master/JWT/JWT.md)

**Comment by shazron** [comment]
Fixed links should point to:
1. https://developer.adobe.com/developer-console/docs/guides/authentication/OAuth/
2. https://developer.adobe.com/developer-console/docs/guides/authentication/JWT/

**Comment by shazron** [comment]
PR #184
