### ISSUE TITLE
Document the app publishing and reviewing flow

### ISSUE THREAD

**Issue by meryllblanchet** [AdobeDocs/project-firefly#39]
Users currently don't find a complete documentation about the application publishing flow from Console to My Exchange to the Experience Cloud.

We should create a dedicated guide for this important piece of Project Firefly.

**Comment by Yu1986** [comment]
https://github.com/AdobeDocs/project-firefly/pull/49
@meryllblanchet @duynguyen

**Comment by meryllblanchet** [comment]
Thanks @Yu1986 for this great contribution!
