### ISSUE TITLE
Document the different validation behaviors for headless vs SPA

### ISSUE THREAD

**Issue by duynguyen** [AdobeDocs/project-firefly#43]
Every other user of the token validation got puzzled by the error message `request is invalid, reason: failed authorization. Please use a valid user token for this SPA.`
Mostly because they are not aware of the distinction of headless vs SPA.
Hence adding an FAQ in the security overview may help.

**Comment by meryllblanchet** [comment]
@duynguyen we already have:

https://github.com/AdobeDocs/project-firefly/blob/master/guides/security_overview.md#securing-the-access-to-headless-project-firefly-applications

https://github.com/AdobeDocs/project-firefly/blob/master/guides/security_overview.md#securing-the-access-to-project-firefly-spas

Could you provide more insights about what distinction is missing in there and we should improve?

Thanks!

**Comment by duynguyen** [comment]
@meryllblanchet , although the current page is very insightful, problem is (I think) less than 5% of the Firefly users read this document before they start building app, then add auth configs, etc. So we have to assume people are not willing to read the theory and need something fast food like "troubleshooting" instructions.
Example: if you see `request is invalid, reason: failed authorization. Please use a valid user token for this SPA.` and are using JWT token, please delete the web-src folder and re-run; for more info pls refer to [Securing the Access to Headless Project Firefly Applications].
Then we refer the questions in slack and forums to this FAQ, which indirectly motivates them to read the theory. Otherwise we have to repeatedly answer the same question 100 times...
I just opened this issue not to forget about it. I can file a PR for it later.

**Comment by meryllblanchet** [comment]
@duynguyen developers must read the docs ;-) 
But I get the point and also think that a concise FAQ section will be helpful. I'll be happy to review your PR!
