### ISSUE TITLE
404 on app hooks docs

### ISSUE THREAD

**Issue by shazron** [AdobeDocs/project-firefly#46]
https://www.adobe.io/apis/experienceplatform/project-firefly/docs.html#!AdobeDocs/project-firefly/master/guides/app-hooks.md

linked from this page: https://www.adobe.io/apis/experienceplatform/project-firefly/docs.html via the link `Extending the CLI App Plugin Commands`

**Comment by meryllblanchet** [comment]
Workaround: access directly from https://github.com/AdobeDocs/project-firefly/blob/master/guides/app-hooks.md.

@sarahxxu I confirm that the page can't be loaded from https://www.adobe.io/apis/experienceplatform/project-firefly/docs.html  and it also doesn't appear in the Guides section in the left navigation.

**Comment by sarahxxu** [comment]
@djwendo i presume this is to do with the website config? could you suggest how we can fix this?

**Comment by djwendo** [comment]
@sarahxxu looks like the app-hooks.md file is missing from the manifest. That would explain why it's not showing in the left-nav as well.

**Comment by djwendo** [comment]
@sarahxxu I can make a PR to update the manifest file to include the missing guide, as a file under the Guides header.

**Comment by djwendo** [comment]
PR with fix has been merged and links are now working as expected.
