### ISSUE TITLE
How to authenticate an external service to hit my "generic" action.

### ISSUE THREAD

**Issue by oliver-foggin** [AdobeDocs/project-firefly#59]
I've been asked to take a look at Project Firefly so trying to work my way through the guides etc...

I'm currently trying to allow an external service to hit the auto-generated `generic` action that is created by the CLI.

At the moment I'm struggling to work out how to authenticate it. I don't know if I should be using an API Token or bearer token or JWT etc... or how to use them.

Would love to get some tips on how to get this running.

Thanks

**Comment by duynguyen** [comment]
Hi @oliver-foggin , you are invited to join our [Experience League Forum](https://experienceleaguecommunities.adobe.com/t5/project-firefly-questions/qa-p/project-firefly-questions) for any technical question about Project Firefly.

In particular, these threads are related to your question:
https://experienceleaguecommunities.adobe.com/t5/project-firefly-questions/adobe-credentials-for-standalone-actions-execution/qaq-p/376236
https://experienceleaguecommunities.adobe.com/t5/project-firefly-questions/openwhisk-alarms-not-allowed-on-local-environment/qaq-p/377034

Feel free to create a new thread in the forum if you have further questions.

**Comment by meryllblanchet** [comment]
Hi @oliver-foggin and thank you for submitting your question!

To complement @duynguyen 's answer, I would like to invite you to also read the [Security Guide](https://github.com/AdobeDocs/project-firefly/blob/master/guides/security_overview.md) if not already done.

Assuming that you will join the Experience League Forum and continue the discussion there, I will close this issue. We're looking forward to getting more feedback from your side about Project Firefly!
